kind: pipeline
name: default



steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodules update --init --recursive

  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.68.3
      validate: true
