kind: pipeline
name: default



steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: klakegg/hugo:0.157.0-ext-alpine
    commands:
      - hugo

  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: philip
      key:
        from_secret: rsync_key
      hosts:
        - docker.rosenberg-watt.com
      source: ./public/
      target: /opt/ipfs/export/blog/
      delete: true
